# Generated by Django 4.2.2 on 2023-06-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influxdb2mysqldb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'robots',
            },
        ),
        migrations.RemoveField(
            model_name='odomtable',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='scantable',
            name='robot',
        ),
        migrations.AlterModelTable(
            name='odomtable',
            table='odom_table',
        ),
        migrations.AlterModelTable(
            name='scantable',
            table='scan_table',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
        migrations.AddField(
            model_name='odomtable',
            name='robots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odom_entries', to='influxdb2mysqldb_app.robots'),
        ),
        migrations.AddField(
            model_name='scantable',
            name='robots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_entries', to='influxdb2mysqldb_app.robots'),
        ),
    ]
