# Generated by Django 4.2.2 on 2023-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influxdb2mysqldb_app', '0006_robots_ip_address_robots_license_robots_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='license',
        ),
    ]
