# Generated by Django 4.2.2 on 2023-06-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('license', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('a_min', models.FloatField(null=True)),
                ('a_max', models.FloatField(null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influxdb2mysqldb_app.robot')),
            ],
        ),
        migrations.CreateModel(
            name='OdomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influxdb2mysqldb_app.robot')),
            ],
        ),
    ]
