# Generated by Django 4.2.2 on 2023-06-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influxdb2mysqldb_app', '0002_robots_remove_odomtable_robot_remove_scantable_robot_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='odomtable',
            table=None,
        ),
        migrations.AlterModelTable(
            name='robots',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scantable',
            table=None,
        ),
    ]
