# Generated by Django 4.2.2 on 2023-06-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influxdb2mysqldb_app', '0005_rename_robots_odomtable_robot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='ip_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='robots',
            name='license',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='robots',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
